CREATE DATABASE catalog_app;

CREATE TABLE Books(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_id INT,
  author_id INT,
  label_id INT,
  publish_date DATE,
  archived BOOLEAN,
  publisher VARCHAR,
  cover_state VARCHAR,

  FOREIGN KEY (genre_id) REFERENCES Genres(id)
  FOREIGN KEY (author_id) REFERENCES Authors(id)
  FOREIGN KEY (label_id) REFERENCES Labels(id)
  FOREIGN KEY (source_id) REFERENCES Sources(id)
)

CREATE TABLE Labels(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  color VARCHAR
)

CREATE TABLE Albums (
  id SERIAL PRIMARY KEY,
  genre_id INT,
  author_id INT,
  label_id INT,
  source_id INT,
  publish_date DATE,
  archived BOOLEAN,
  on_spotify BOOLEAN,
  name VARCHAR(100)

  FOREIGN KEY (genre_id) REFERENCES Genres(id)
  FOREIGN KEY (author_id) REFERENCES Authors(id)
  FOREIGN KEY (label_id) REFERENCES Labels(id)
  FOREIGN KEY (source_id) REFERENCES Sources(id)
)

CREATE TABLE Genres (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100)
)

CREATE TABLE Author (
  id INT,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  PRIMARY KEY (id)
);

CREATE TABLE Game (
  id INT,
  multiplayer VARCHAR(100),
  last_played_at VARCHAR(100),
  publish_date Date,
  archived Boolean,
  label_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (label_id) REFERENCES Labels(id)
);



